version: '3.8'

services:
  bot:
    build: .
    command: [ "python", "main.py", "--prod", "--log-file=/var/log/bot.log" ]
    volumes:
      - bot_logs:/var/log
    environment:
      - CLOUDFLARE_BYPASS_PORT=${CLOUDFLARE_BYPASS_PORT}
      - TELEGRAM_API_PORT=${TELEGRAM_API_PORT}
      - TRANSLATE_KEY_ID=${TRANSLATE_KEY_ID}
      - TRANSLATE_KEY_SECRET=${TRANSLATE_KEY_SECRET}
    depends_on:
      - telegram_api
      - cloudflare-bypass

  telegram_api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_HTTP_PORT: 8081
      TELEGRAM_LOCAL: ""
      TELEGRAM_WORK_DIR: "/data"
      # TELEGRAM_LOG_FILE: "./log.log"
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - telegram_data:/data
    ports:
      - "${TELEGRAM_API_PORT}:8081"

  cloudflare-bypass:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    ports:
      - "$CLOUDFLARE_PORT:8000"

volumes:
  bot_logs:
  telegram_data:
